TEAM_FLAGS: dict[str, str] = {
    # 2026 WC teams
    "Mexico":                 "🇲🇽",
    "Czech Republic":         "🇨🇿",
    "South Korea":            "🇰🇷",
    "South Africa":           "🇿🇦",
    "Canada":                 "🇨🇦",
    "Bosnia and Herzegovina": "🇧🇦",
    "Switzerland":            "🇨🇭",
    "Qatar":                  "🇶🇦",
    "Brazil":                 "🇧🇷",
    "Scotland":               "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Haiti":                  "🇭🇹",
    "Morocco":                "🇲🇦",
    "Paraguay":               "🇵🇾",
    "Turkey":                 "🇹🇷",
    "Australia":              "🇦🇺",
    "United States":          "🇺🇸",
    "Ecuador":                "🇪🇨",
    "Germany":                "🇩🇪",
    "Ivory Coast":            "🇨🇮",
    "Curaçao":                "🇨🇼",
    "Netherlands":            "🇳🇱",
    "Sweden":                 "🇸🇪",
    "Japan":                  "🇯🇵",
    "Tunisia":                "🇹🇳",
    "Belgium":                "🇧🇪",
    "Iran":                   "🇮🇷",
    "Egypt":                  "🇪🇬",
    "New Zealand":            "🇳🇿",
    "Spain":                  "🇪🇸",
    "Uruguay":                "🇺🇾",
    "Saudi Arabia":           "🇸🇦",
    "Cape Verde":             "🇨🇻",
    "France":                 "🇫🇷",
    "Norway":                 "🇳🇴",
    "Iraq":                   "🇮🇶",
    "Senegal":                "🇸🇳",
    "Argentina":              "🇦🇷",
    "Austria":                "🇦🇹",
    "Algeria":                "🇩🇿",
    "Jordan":                 "🇯🇴",
    "Portugal":               "🇵🇹",
    "Colombia":               "🇨🇴",
    "Uzbekistan":             "🇺🇿",
    "DR Congo":               "🇨🇩",
    "England":                "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Croatia":                "🇭🇷",
    "Panama":                 "🇵🇦",
    "Ghana":                  "🇬🇭",
    # Other common footballing nations
    "Italy":                  "🇮🇹",
    "Russia":                 "🇷🇺",
    "Ukraine":                "🇺🇦",
    "Poland":                 "🇵🇱",
    "Denmark":                "🇩🇰",
    "Serbia":                 "🇷🇸",
    "Hungary":                "🇭🇺",
    "Romania":                "🇷🇴",
    "Greece":                 "🇬🇷",
    "Slovakia":               "🇸🇰",
    "Slovenia":               "🇸🇮",
    "Albania":                "🇦🇱",
    "North Macedonia":        "🇲🇰",
    "Iceland":                "🇮🇸",
    "Wales":                  "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Ireland":                "🇮🇪",
    "Northern Ireland":       "🇬🇧",
    "China":                  "🇨🇳",
    "India":                  "🇮🇳",
    "Chile":                  "🇨🇱",
    "Peru":                   "🇵🇪",
    "Venezuela":              "🇻🇪",
    "Bolivia":                "🇧🇴",
    "Costa Rica":             "🇨🇷",
    "Honduras":               "🇭🇳",
    "Jamaica":                "🇯🇲",
    "Cuba":                   "🇨🇺",
    "El Salvador":            "🇸🇻",
    "Guatemala":              "🇬🇹",
    "Nigeria":                "🇳🇬",
    "Cameroon":               "🇨🇲",
    "Senegal":                "🇸🇳",
    "Mali":                   "🇲🇱",
    "Burkina Faso":           "🇧🇫",
    "Kenya":                  "🇰🇪",
    "Tanzania":               "🇹🇿",
    "Ethiopia":               "🇪🇹",
    "Zambia":                 "🇿🇲",
    "Zimbabwe":               "🇿🇼",
    "Mozambique":             "🇲🇿",
    "Angola":                 "🇦🇴",
    "Namibia":                "🇳🇦",
    "Botswana":               "🇧🇼",
    "Libya":                  "🇱🇾",
    "Sudan":                  "🇸🇩",
    "South Sudan":            "🇸🇸",
    "Togo":                   "🇹🇬",
    "Benin":                  "🇧🇯",
    "Equatorial Guinea":      "🇬🇶",
    "Gabon":                  "🇬🇦",
    "Rwanda":                 "🇷🇼",
    "Uganda":                 "🇺🇬",
    "Mauritius":              "🇲🇺",
    "Comoros":                "🇰🇲",
    "Djibouti":               "🇩🇯",
    "Eritrea":                "🇪🇷",
    "Somalia":                "🇸🇴",
    "Thailand":               "🇹🇭",
    "Vietnam":                "🇻🇳",
    "Indonesia":              "🇮🇩",
    "Malaysia":               "🇲🇾",
    "Philippines":            "🇵🇭",
    "Myanmar":                "🇲🇲",
    "Cambodia":               "🇰🇭",
    "Laos":                   "🇱🇦",
    "Singapore":              "🇸🇬",
    "Mongolia":               "🇲🇳",
    "Afghanistan":            "🇦🇫",
    "Pakistan":               "🇵🇰",
    "Bangladesh":             "🇧🇩",
    "Nepal":                  "🇳🇵",
    "Sri Lanka":              "🇱🇰",
    "Bhutan":                 "🇧🇹",
    "Maldives":               "🇲🇻",
    "Kazakhstan":             "🇰🇿",
    "Kyrgyzstan":             "🇰🇬",
    "Tajikistan":             "🇹🇯",
    "Turkmenistan":           "🇹🇲",
    "Azerbaijan":             "🇦🇿",
    "Georgia":                "🇬🇪",
    "Armenia":                "🇦🇲",
    "Moldova":                "🇲🇩",
    "Belarus":                "🇧🇾",
    "Latvia":                 "🇱🇻",
    "Lithuania":              "🇱🇹",
    "Estonia":                "🇪🇪",
    "Finland":                "🇫🇮",
    "Kosovo":                 "🇽🇰",
    "Montenegro":             "🇲🇪",
    "Cyprus":                 "🇨🇾",
    "Luxembourg":             "🇱🇺",
    "Malta":                  "🇲🇹",
    "Andorra":                "🇦🇩",
    "Liechtenstein":          "🇱🇮",
    "San Marino":             "🇸🇲",
    "Gibraltar":              "🇬🇮",
    "Israel":                 "🇮🇱",
    "Palestine":              "🇵🇸",
    "Lebanon":                "🇱🇧",
    "Syria":                  "🇸🇾",
    "Yemen":                  "🇾🇪",
    "Oman":                   "🇴🇲",
    "United Arab Emirates":   "🇦🇪",
    "Kuwait":                 "🇰🇼",
    "Bahrain":                "🇧🇭",
    "Turkiye":                "🇹🇷",
}


def flag(team: str) -> str:
    """Return the emoji flag for a team, or empty string if unknown."""
    return TEAM_FLAGS.get(team, "")


def with_flag(team: str) -> str:
    """Return 'FLAG Team' string, or just 'Team' if no flag found."""
    f = TEAM_FLAGS.get(team, "")
    return f"{f} {team}" if f else team
